AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false