# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  run-minitest:
    docker:
      - image: cimg/ruby:2.6.6-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: swedish-birds_test

    steps:
      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run: |
          bundle config set path 'vendor/bundle'
          .circleci/bin/install-same-bundler-version.sh
          bundle check || bundle install
      - run: sudo apt install -y postgresql-client || true
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
      - run:
          command: bundle exec rake test
          when: always
      - store_test_results:
          path: test/reports

workflows:
  run-minitest-workflow:
    jobs:
      - run-minitest
